# Generated by Django 4.1.2 on 2022-12-19 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("river", "0006_spotdata_collected_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bouy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=20)),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bouy",
                        to="river.spot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BouyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salinity", models.FloatField()),
                ("waterlevel", models.FloatField()),
                ("tempreture", models.FloatField()),
                ("battery_percentage", models.FloatField()),
                ("consume_rate", models.FloatField()),
                (
                    "bouy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="bouy.bouy",
                    ),
                ),
                (
                    "spot_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bouy_data",
                        to="river.spotdata",
                    ),
                ),
            ],
        ),
    ]
