# Generated by Django 4.1.4 on 2022-12-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bouy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField()),
                ("latitude", models.FloatField()),
                ("longtitude", models.FloatField()),
            ],
        ),
    ]
