# Generated by Django 4.1.4 on 2023-01-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bouy", "0002_watergate"),
    ]

    operations = [
        migrations.AddField(
            model_name="watergate",
            name="serial_number",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
