# Generated by Django 4.1.5 on 2023-01-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bouy", "0003_watergate_serial_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="bouydata", name="tempreture",),
        migrations.AddField(
            model_name="bouydata",
            name="airpressure",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
