# Generated by Django 4.1.5 on 2023-01-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bouy", "0004_remove_bouydata_tempreture_bouydata_airpressure"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bouydata", old_name="consume_rate", new_name="airtempreture",
        ),
        migrations.AddField(
            model_name="bouydata",
            name="latitude",
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bouydata",
            name="longtitude",
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
