# Generated by Django 4.1.5 on 2023-01-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bouy", "0005_rename_consume_rate_bouydata_airtempreture_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="bouydata", name="battery_percentage",),
    ]
