# Generated by Django 4.1.6 on 2023-02-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bouy', '0008_remove_bouydata_bouy_remove_bouydata_spot_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterGate',
        ),
    ]
