# Generated by Django 4.1.2 on 2022-12-18 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0002_bouy_spot_spotdata_bouydata_bouy_spot"),
    ]

    operations = [
        migrations.RemoveField(model_name="bouydata", name="bouy",),
        migrations.DeleteModel(name="Bouy",),
        migrations.DeleteModel(name="BouyData",),
    ]
