# Generated by Django 4.1.2 on 2022-12-18 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0003_remove_bouydata_bouy_delete_bouy_delete_bouydata"),
    ]

    operations = [
        migrations.RemoveField(model_name="river", name="code",),
    ]
