# Generated by Django 4.1.2 on 2022-12-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0004_remove_river_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="river",
            name="code",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
