# Generated by Django 4.1.2 on 2022-12-18 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0005_river_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotdata",
            name="collected_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
