# Generated by Django 4.1.2 on 2022-12-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0006_spotdata_collected_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="spot",
            name="name",
            field=models.CharField(default="p", max_length=255),
            preserve_default=False,
        ),
    ]
