# Generated by Django 4.1.2 on 2022-12-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0007_spot_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="spot",
            name="code",
            field=models.CharField(default="pluem", max_length=6),
            preserve_default=False,
        ),
    ]
