# Generated by Django 4.1.5 on 2023-01-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0008_spot_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spotdata", old_name="tempreture", new_name="latitude",
        ),
        migrations.RenameField(
            model_name="spotdata", old_name="watervelocity", new_name="longtitude",
        ),
    ]
