# Generated by Django 4.1.5 on 2023-01-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0009_rename_tempreture_spotdata_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotdata",
            name="airpressure",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
