# Generated by Django 4.1.5 on 2023-01-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0011_spot_predicted_waterlevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotdata",
            name="maxwaterlevel",
            field=models.FloatField(default=2.17),
            preserve_default=False,
        ),
    ]
