# Generated by Django 4.1.5 on 2023-01-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0012_spotdata_maxwaterlevel"),
    ]

    operations = [
        migrations.RemoveField(model_name="spotdata", name="maxwaterlevel",),
        migrations.AddField(
            model_name="spot",
            name="maxwaterlevel",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
