# Generated by Django 4.1.5 on 2023-01-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0013_remove_spotdata_maxwaterlevel_spot_maxwaterlevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotdata",
            name="airtempreture",
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
