# Generated by Django 4.1.5 on 2023-01-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0014_spotdata_airtempreture"),
    ]

    operations = [
        migrations.RemoveField(model_name="spotdata", name="latitude",),
        migrations.RemoveField(model_name="spotdata", name="longtitude",),
    ]
