# Generated by Django 4.1.5 on 2023-01-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0016_spotdata_predictvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotdata",
            name="predictvalue2",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
