# Generated by Django 4.1.5 on 2023-01-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bouy", "0006_remove_bouydata_battery_percentage"),
        ("river", "0017_spotdata_predictvalue2"),
    ]

    operations = [
        migrations.RenameModel(old_name="SpotData", new_name="DailySpotData",),
    ]
