# Generated by Django 4.1.5 on 2023-01-31 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0018_rename_spotdata_dailyspotdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyspotdata",
            name="collected_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="dailyspotdata",
            name="spot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dailydata",
                to="river.spot",
            ),
        ),
    ]
