# Generated by Django 4.1.5 on 2023-01-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0019_alter_dailyspotdata_collected_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collected_date", models.DateTimeField(auto_now_add=True)),
                ("salinity", models.FloatField()),
                ("waterlevel", models.FloatField()),
                ("airpressure", models.FloatField()),
                ("airtempreture", models.FloatField()),
            ],
        ),
    ]
