# Generated by Django 4.1.5 on 2023-01-31 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0020_spotdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotdata",
            name="daily",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indaydata",
                to="river.dailyspotdata",
            ),
            preserve_default=False,
        ),
    ]
