# Generated by Django 4.1.5 on 2023-01-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0021_spotdata_daily"),
    ]

    operations = [
        migrations.AddField(
            model_name="spot",
            name="serial_number",
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
