# Generated by Django 4.1.5 on 2023-01-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0022_spot_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="spot",
            name="serial",
            field=models.CharField(default=12, max_length=3),
            preserve_default=False,
        ),
    ]
