# Generated by Django 4.1.5 on 2023-01-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0023_spot_serial"),
    ]

    operations = [
        migrations.RemoveField(model_name="spot", name="serial",),
        migrations.AlterField(
            model_name="spot",
            name="serial_number",
            field=models.CharField(max_length=3),
        ),
    ]
