# Generated by Django 4.1.5 on 2023-01-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0024_remove_spot_serial_alter_spot_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotdata",
            name="latitude",
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spotdata",
            name="longitude",
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
