# Generated by Django 4.1.5 on 2023-02-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0026_riverforecast"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotdata",
            name="collected_spot",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indaydata",
                to="river.spot",
            ),
            preserve_default=False,
        ),
    ]
