# Generated by Django 4.1.6 on 2023-02-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0029_remove_predictiongroup_river_delete_prediction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watervalue', models.FloatField()),
                ('salvalue', models.FloatField()),
                ('dailyspotdata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spot_forecast', to='river.dailyspotdata')),
            ],
        ),
        migrations.RemoveField(
            model_name='riverforecast',
            name='dailyspotdata',
        ),
        migrations.DeleteModel(
            name='SpotWaterLevelForecast',
        ),
        migrations.AddField(
            model_name='spotforecast',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_forecast', to='river.riverforecast'),
        ),
        migrations.AddField(
            model_name='spotforecast',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='river.spot'),
        ),
    ]
