# Generated by Django 4.1.6 on 2023-02-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0030_spotforecast_remove_riverforecast_dailyspotdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotdata',
            name='predictvalue',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotdata',
            name='predictvalue2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
